version: '3'
services:
  frontend:
    build: /home/ubuntu/rkcart
    ports:
      - "80:80"

  backend:
    build: /home/ubuntu/beserver
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: demo
    volumes:
      - db_data:/var/lib/postgresql/data  

volumes:
  db_data:
